//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34003 版自动生成。
// 
#pragma warning disable 1591

namespace CaptureDevSys.com.zjwist.qy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CarStatByDaySoap", Namespace="http://tempuri.org/")]
    public partial class CarStatByDay : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback StatByDayOperationCompleted;
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback WithOutCarInfoMore30MinOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMsgForCarToAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMsgForCarToALLOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CarStatByDay() {
            this.Url = global::CaptureDevSys.Properties.Settings.Default.CaptureDevSys_com_zjwist_qy_CarStatByDay;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event StatByDayCompletedEventHandler StatByDayCompleted;
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event WithOutCarInfoMore30MinCompletedEventHandler WithOutCarInfoMore30MinCompleted;
        
        /// <remarks/>
        public event SendMsgForCarToAdminCompletedEventHandler SendMsgForCarToAdminCompleted;
        
        /// <remarks/>
        public event SendMsgForCarToALLCompletedEventHandler SendMsgForCarToALLCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StatByDay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void StatByDay(int unitid, string carday) {
            this.Invoke("StatByDay", new object[] {
                        unitid,
                        carday});
        }
        
        /// <remarks/>
        public void StatByDayAsync(int unitid, string carday) {
            this.StatByDayAsync(unitid, carday, null);
        }
        
        /// <remarks/>
        public void StatByDayAsync(int unitid, string carday, object userState) {
            if ((this.StatByDayOperationCompleted == null)) {
                this.StatByDayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStatByDayOperationCompleted);
            }
            this.InvokeAsync("StatByDay", new object[] {
                        unitid,
                        carday}, this.StatByDayOperationCompleted, userState);
        }
        
        private void OnStatByDayOperationCompleted(object arg) {
            if ((this.StatByDayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StatByDayCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WithOutCarInfoMore30Min", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void WithOutCarInfoMore30Min() {
            this.Invoke("WithOutCarInfoMore30Min", new object[0]);
        }
        
        /// <remarks/>
        public void WithOutCarInfoMore30MinAsync() {
            this.WithOutCarInfoMore30MinAsync(null);
        }
        
        /// <remarks/>
        public void WithOutCarInfoMore30MinAsync(object userState) {
            if ((this.WithOutCarInfoMore30MinOperationCompleted == null)) {
                this.WithOutCarInfoMore30MinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWithOutCarInfoMore30MinOperationCompleted);
            }
            this.InvokeAsync("WithOutCarInfoMore30Min", new object[0], this.WithOutCarInfoMore30MinOperationCompleted, userState);
        }
        
        private void OnWithOutCarInfoMore30MinOperationCompleted(object arg) {
            if ((this.WithOutCarInfoMore30MinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WithOutCarInfoMore30MinCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMsgForCarToAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendMsgForCarToAdmin(string msg) {
            this.Invoke("SendMsgForCarToAdmin", new object[] {
                        msg});
        }
        
        /// <remarks/>
        public void SendMsgForCarToAdminAsync(string msg) {
            this.SendMsgForCarToAdminAsync(msg, null);
        }
        
        /// <remarks/>
        public void SendMsgForCarToAdminAsync(string msg, object userState) {
            if ((this.SendMsgForCarToAdminOperationCompleted == null)) {
                this.SendMsgForCarToAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMsgForCarToAdminOperationCompleted);
            }
            this.InvokeAsync("SendMsgForCarToAdmin", new object[] {
                        msg}, this.SendMsgForCarToAdminOperationCompleted, userState);
        }
        
        private void OnSendMsgForCarToAdminOperationCompleted(object arg) {
            if ((this.SendMsgForCarToAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMsgForCarToAdminCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMsgForCarToALL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendMsgForCarToALL(string msg) {
            this.Invoke("SendMsgForCarToALL", new object[] {
                        msg});
        }
        
        /// <remarks/>
        public void SendMsgForCarToALLAsync(string msg) {
            this.SendMsgForCarToALLAsync(msg, null);
        }
        
        /// <remarks/>
        public void SendMsgForCarToALLAsync(string msg, object userState) {
            if ((this.SendMsgForCarToALLOperationCompleted == null)) {
                this.SendMsgForCarToALLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMsgForCarToALLOperationCompleted);
            }
            this.InvokeAsync("SendMsgForCarToALL", new object[] {
                        msg}, this.SendMsgForCarToALLOperationCompleted, userState);
        }
        
        private void OnSendMsgForCarToALLOperationCompleted(object arg) {
            if ((this.SendMsgForCarToALLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMsgForCarToALLCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void StatByDayCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void WithOutCarInfoMore30MinCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SendMsgForCarToAdminCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void SendMsgForCarToALLCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591